apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd-1
spec:
  selector:
    matchLabels:
      app: test-cicd-1
  replicas: 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-cicd-1
    spec:
      containers:
        - name: test-cicd-1
          image: us-central1-docker.pkg.dev/test-cicd-1/test-cicd-1/test-cicd-1
          ports:
           - containerPort: 3000
# <location>-docker.pkg.dev/project/repo/image